version: '3.8'

services:
  mongo1:
    image: mongo:latest
    container_name: mongo1
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo2:
    image: mongo:latest
    container_name: mongo2
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo3:
    image: mongo:latest
    container_name: mongo3
    ports:
      - 27019:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-config:
    image: mongo:latest
    container_name: mongo-config
    command: mongod --configsvr --replSet configReplSet --port 27017
    ports:
      - 27020:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-router:
    image: mongo:latest
    container_name: mongo-router
    command: mongos --configdb configReplSet/mongo-config:27017 --bind_ip_all
    ports:
      - 27021:27017

networks:
  default:
    driver: bridge
